stages:
 - verify

before_script:
  - pwd
  - ls -al

lint:
  stage: verify
  image: docker.io/golangci/golangci-lint:v1.56.2
  allow_failure: false
  tags:
    - shared-runners-no-root
  only:
    refs:
      - merge_requests
      - main
  script:
    - make lint
