stages:
  - deploy

deploy_to_github:
  stage: deploy
  script:
    - |
      if ! git remote | grep -q "github"; then
        git remote add github https://github.com/jiasyuanchu/testing-cicd.git
      fi
    - git push github main
